### PR TITLE
Reset token

### PR DESCRIPTION
**Pull request by jan-janssen**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@jan-janssen, this is probably harmless but there is no need to push the build number to reset tokens, you just need to push an empty commit to `main`.

**Comment by jan-janssen** [comment]
@xylar thanks. As I am currently on the go, is it possible to push an empty commit via the web interface?

**Comment by xylar** [comment]
Not that I'm aware of, it has to be done at the command line.  You could just make a dummy edit to the README and push that, though.

**Pull request merged**
